name: Docker Build and Push

on:
  push:
    branches:
      - main  # Définissez la branche sur laquelle déclencher la pipeline (changez-la si nécessaire)

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker image
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker buildx create --use
        docker buildx inspect --bootstrap

        docker build -t my-docker-image:latest .
        docker login docker.pkg.github.com -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker tag my-docker-image:latest docker.pkg.github.com/ilyesb36/any-repository-name/my-docker-image:latest
        docker push docker.pkg.github.com/ilyesb36/any-repository-name/my-docker-image:latest
